name: Spell checking
on: [push, pull_request]

jobs:
  spelling:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - name: checkout-merge
      uses: actions/checkout@v2
      with:
        ref: refs/pull/${{github.event.pull_request.number}}/merge
    - name: checkout
      uses: actions/checkout@v2
    - uses: check-spelling/check-spelling@main
